In [12]:
import numpy as np
list = [1,2,3,4,5]
print(list[0])
list1= ['hello',1,2,True,list]
print(list1)
np1= np.array([5,6,7,8,9])
print(np1)
print(np1.shape)
#range
np2=np.arange(10)
print(np2)
#step
np3=np.arange(0,10,2)
print(np3)
#zeros
np4 = np.zeros(10)
print(np4)
#multidimensional zeros
np5 = np.zeros((2,10))
print(np5)
#full
np6 = np.full((10),6)
print(np6)
#multidimensional full
np7 = np.full((2,10),6)
print(np7)
#convert list to numpy
list3 = [4,5,6,7]
np8 = np.array(list3)
print(np8)
print(np8[0])

1
['hello', 1, 2, True, [1, 2, 3, 4, 5]]
[5 6 7 8 9]
(5,)
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[6 6 6 6 6 6 6 6 6 6]
[[6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6]]
[4 5 6 7]
4
