In [3]:
import numpy as np
np1=np.array([1,2,3,4,5,6,7,8,9,10,3])
x=np.where(np1 == 3)
print(x[0])
print(np1[x[0]])
y=np.where(np1%2 == 0)
print(y[0])
print(np1[y[0]])
z=np.where(np1 % 2 != 0)
print(z[0])
print(np1[z[0]])

[ 2 10]
[3 3]
[1 3 5 7 9]
[ 2  4  6  8 10]
[ 0  2  4  6  8 10]
[1 3 5 7 9 3]
