In [2]:
import numpy as np
np1 = np.array([1,2,3,4,5,6,7,8,9])
# PRINT 2,3,4,5
print(np1[1:6])
#print from something till end
print(np1[3:])
#from back 7,8
print(np1[-3:-1])
#steps
print(np1[1:5:2])
print(np1[::3])
#2-D slicing
np2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
#pulling an element
print(np2[1,2])
print(np2[0:1,0:3])
print(np2[0:2,1:3])


[2 3 4 5 6]
[4 5 6 7 8 9]
[7 8]
[2 4]
[1 4 7]
8
[[1 2 3]]
[[2 3]
 [7 8]]
