In [2]:
import numpy  as np
np1=np.array([7,2,4,1])
np2=np.sort(np1)
print(np1)
print(np2)

[7 2 4 1]
[1 2 4 7]


In [5]:
np3 = np.array(["aaron","zed","bhavika","john"])
print(np3)
print(np.sort(np3))
np4=np.array([True,False,True,False])
print(np4)
print(np.sort(np4))

['aaron' 'zed' 'bhavika' 'john']
['aaron' 'bhavika' 'john' 'zed']
[ True False  True False]
[False False  True  True]


In [6]:
np5=np.array([[1,8,4,9],[6,4,7,2]])
print(np5)
print(np.sort(np5))

[[1 8 4 9]
 [6 4 7 2]]
[[1 4 8 9]
 [2 4 6 7]]
