In [4]:
import numpy  as np
np1 = np.array([-3,-2,-1,0,1,2,3,4,5,6,7,8,9])
print(np1)

#sqrt
print(np.sqrt(np1))

#absolute
print(np.absolute(np1))

#sin
print(np.sin(np1))

#log
print(np.log(np1))

#expotential
print(np.exp(np1))

#min and max
print(np.max(np1))
print(np.min(np1))
#sign
print(np.sign(np1))

[-3 -2 -1  0  1  2  3  4  5  6  7  8  9]
[       nan        nan        nan 0.         1.         1.41421356
 1.73205081 2.         2.23606798 2.44948974 2.64575131 2.82842712
 3.        ]
[3 2 1 0 1 2 3 4 5 6 7 8 9]
[-0.14112001 -0.90929743 -0.84147098  0.          0.84147098  0.90929743
  0.14112001 -0.7568025  -0.95892427 -0.2794155   0.6569866   0.98935825
  0.41211849]
[       nan        nan        nan       -inf 0.         0.69314718
 1.09861229 1.38629436 1.60943791 1.79175947 1.94591015 2.07944154
 2.19722458]
[4.97870684e-02 1.35335283e-01 3.67879441e-01 1.00000000e+00
 2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]
9
-3
[-1 -1 -1  0  1  1  1  1  1  1  1  1  1]


C:\Users\Bhavika\AppData\Local\Temp\ipykernel_12796\626191994.py:6: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(np1))
C:\Users\Bhavika\AppData\Local\Temp\ipykernel_12796\626191994.py:15: RuntimeWarning: divide by zero encountered in log
  print(np.log(np1))
C:\Users\Bhavika\AppData\Local\Temp\ipykernel_12796\626191994.py:15: RuntimeWarning: invalid value encountered in log
  print(np.log(np1))
